language: generic
sudo: false

# TODO: tmp, remove before merge
git:
  depth: 100

os:
  - linux

cache:
  directories:
    - $HOME/miniconda

before_cache:
  - rm -rf $HOME/miniconda/pkgs
  - rm -rf $HOME/miniconda/conda-bld
  - rm -rf $HOME/miniconda/envs/*/conda-bld

env:
  global:
    - PYENV_VERSION=3.6
    - PKG_TEST_PYTHON="--test-python=py36 --test-python=py27"
    - CHANS_DEV="-c pyviz/label/dev -c ioam"
    - CHANS="-c pyviz -c ioam"

# quick hack to determine what tag means (improvements welcome)
#     release: ^v(\d+|\.)*[^a-z]\d*$
# dev release: ^v(\d+|\.)*[a-z]\d*$

stages:
  - test
  - name: conda_dev_package
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$  
  - name: pip_dev_package
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
  - name: docs
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
  # TODO: add release packages and release docs (future PR)

jobs:
  include:
    ########## DEVELOPER INSTALL ##########

    - &default
      stage: test
      env: DESC="dev test_all_recommended"
      before_install:
        - pip install pyct && doit miniconda_install && pip uninstall -y doit pyct
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        - conda install -c pyviz/label/dev pyct && doit ecosystem_setup
      install:
        - doit env_create $CHANS_DEV --python=$PYENV_VERSION
        - source activate test-environment
        - doit develop_install $CHANS_DEV -o recommended
        - doit env_capture
      script:
        - geoviews fetch-data --path=examples
        - bokeh sampledata
        - doit test_all_recommended
      after_success: coveralls

    # python 2 flake checking typically catches python 2 syntax
    # errors where python 3's been assumed...
    - <<: *default
      env: DESC="py2 flakes" PYENV_VERSION=2.7
      script: doit test_flakes

    ########## DOCS ##########

    - <<: *default
      stage: docs
      # not possible to run all examples to build website using only defaults (see setup.py)
      env: DESC="docs" CHANS_DEV="-c pyviz/label/dev -c ioam -c conda-forge"
      script:
        - doit develop_install $CHANS_DEV -o doc
        - geoviews fetch-data --path=examples
        - bokeh sampledata
        - rm examples/Colocated_cube_pair.ipynb examples/CubeExplorer_Prototype.ipynb # not currently part of website
        # note: will vastly simplified in a future version of nbsite
        - cd doc
        - nbsite_nbpagebuild.py ioam geoviews ../examples .     
        ### gallery
        - ln -s ../examples/assets assets
        - ln -s ../examples/data data
        - nbsite_gallery.py .. examples None '.' matplotlib bokeh None
        ###
        - sphinx-build -b html . ./_build/html
        - nbsite_fix_links.py _build/html
        - nbsite_cleandisthtml.py ./_build/html take_a_chance
        - touch ./_build/html/.nojekyll
        - cd ..
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: ./doc/_build/html
          repo: ioam-docs/geoviews-dev


    ########## END-USER PACKAGES ##########

    ## dev packages

    - <<: *default
      stage: conda_dev_package
      env: DESC="" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit package_build --recipe=core $CHANS_DEV $PKG_TEST_PYTHON --test-group=unit
        - doit package_build --recipe=recommended $CHANS_DEV $PKG_TEST_PYTHON --test-group=examples
      script:
        # TODO: going to anaconda.org/ceball temporarily
        - doit package_upload --user=ceball --token=$CEBTMP --label=dev --recipe=core
        - doit package_upload --user=ceball --token=$CEBTMP --label=dev --recipe=recommended

    # Awkward because we use conda for gv's dependencies when making
    # the pip package (something pyct does not support, but could)
    - <<: *default
      stage: pip_dev_package
      env: PYPI="https://test.pypi.org/legacy/" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        # install deps using conda
        - doit develop_install $CHANS_DEV -o tests && pip uninstall -y geoviews
        # some ecosystem=pip build tools must be installed with conda when using conda...
        - conda install -y pip twine wheel
        # ..and some are only available via conda-forge
        - conda install -y -c conda-forge tox virtualenv
        # this interferes with pip-installed nose
        - conda remove -y --force nose
        # now carry on as normal
        - doit ecosystem=pip package_build --test-python=py36 --test-group=unit
      script: doit ecosystem=pip package_upload -u $TPPU -p $TPPP -r ${PYPI}
